apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus2
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  storage:
    class: ssd
    selector:
      matchLabels:
        name: ssd-prom-claim
    resources:
      requests:
        storage: 10Gi
    volumeClaimTemplate:
      metadata:
        name: ssd-prom-claim
      spec:
        storageClassName: ssd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi