apiVersion: batch/v1
kind: Job
metadata:
  name: clone_db
spec:
  template:
    spec:
      containers:
      - name: psql
        image: postgres
        command:
          - psql
          - --host=$PG_HOST
          - --port=$PG_PORT
          - --username=$PG_USERNAME
          - --password=$PG_PASSWORD
        env:
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: host
          - name: PGPORT
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: port
          - name: PGUSERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: uername
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
      restartPolicy: Never
  backoffLimit: 4
