apiVersion: batch/v1
kind: Job
metadata:
  name: dbjob
spec:
  template:
    spec:
      containers:
      - name: psql
        image: postgres
        command:
          - psql
          - --host=$PGHOST
          - --port=$PGPORT
          - --username=$PGUSERNAME
        env:
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: host
          - name: PGPORT
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: port
          - name: PGUSERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: uername
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
      restartPolicy: Never
  backoffLimit: 4
