apiVersion: v1
kind: ServiceAccount
metadata:
  name: klstr
  namespace: klstr
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: klstr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: klstr
    namespace: klstr
