apiVersion: extensions/v1beta1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres01
        image: postgres
        ports:
        - containerPort: 5432
          name: pgport
        env:
        - name: POSTGRES_PASSWORD
          value: "Password123!"
        volumeMounts:
        - name: pg
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pg
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi